/*
 * PetsExceptions.h
 *
 *  Created on: Aug 8, 2013
 *      Author: juergens
 */

#ifndef PETSEXCEPTIONS_H_
#define PETSEXCEPTIONS_H_



/*
 $Id$

 Copyright (C) 2006 met.no

 Contact information:
 Norwegian Meteorological Institute
 Box 43 Blindern
 0313 OSLO
 NORWAY
 email: diana@met.no

 This file is part of generated by met.no

 This is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 This is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Tseries; if not, write to the Free Software
 Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */

#include <exception>
#include <string>

// exceptions for the pets library

namespace pets {


class PetsException : public std::exception {
private:
  std::string message;
public:
  PetsException() {}
  ~PetsException() throw(){}

  void setMessage(std::string msg){message=msg;}

  const char* what() const throw()  {
    return (message.empty() ? "PetsException" :  message.c_str());
  }
};


class FimexstreamException : public PetsException {
public:
  FimexstreamException(std::string m="") {setMessage(std::string("Exception from Fimexstream: ")+m);}
  ~FimexstreamException() throw(){}
};


}; // pets



#endif /* PETSEXCEPTIONS_H_ */
