/*
 * WdbCacheQuery.h
 *
 *  Created on: Apr 22, 2010
 *      Author: juergens
 */

#ifndef WDBCACHEQUERY_H_
#define WDBCACHEQUERY_H_

/*
 $Id$

 Copyright (C) 2006 met.no

 Contact information:
 Norwegian Meteorological Institute
 Box 43 Blindern
 0313 OSLO
 NORWAY
 email: diana@met.no

 This file is part of generated by met.no

 This is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 This is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Tseries; if not, write to the Free Software
 Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */


#include <pqxx/pqxx>
#include <string>
#include "WdbQueries.h"

namespace pets
{

class WdbCacheQuery {
  pqxx::connection wdb;
  std::string user;
public:
  WdbCacheQuery(std::string host, std::string u="proffread") : wdb( QUERY::CONNECT(host,u) ) , user(u) {}
  bool sendCacheQuery(std::string model, std::string run, std::vector<std::string> parameters, std::string height="NULL");
};

}

#endif /* WDBCACHEQUERY_H_ */
